
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xlinearstretch.h"

/*
* The configuration table for devices
*/

XLinearstretch_Config XLinearstretch_ConfigTable[XPAR_XLINEARSTRETCH_NUM_INSTANCES] =
{
	{
		XPAR_LINEARSTRETCH_0_DEVICE_ID,
		XPAR_LINEARSTRETCH_0_S_AXI_CRTL_BUS_BASEADDR
	}
};


