set_property PACKAGE_PIN B17 [get_ports {emc_rtl_0_dq_io[7]}]
set_property PACKAGE_PIN F18 [get_ports {emc_rtl_0_dq_io[0]}]
set_property PACKAGE_PIN F17 [get_ports {emc_rtl_0_dq_io[1]}]
set_property PACKAGE_PIN E18 [get_ports {emc_rtl_0_dq_io[2]}]
set_property PACKAGE_PIN E17 [get_ports {emc_rtl_0_dq_io[3]}]
set_property PACKAGE_PIN D18 [get_ports {emc_rtl_0_dq_io[4]}]
set_property PACKAGE_PIN C18 [get_ports {emc_rtl_0_dq_io[5]}]
set_property PACKAGE_PIN C17 [get_ports {emc_rtl_0_dq_io[6]}]
set_property PACKAGE_PIN U14 [get_ports spi_rtl_0_io0_io]
set_property PACKAGE_PIN U11 [get_ports spi_rtl_0_io1_io]
set_property PACKAGE_PIN U15 [get_ports spi_rtl_0_io2_io]
set_property PACKAGE_PIN V13 [get_ports spi_rtl_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Clk100]
set_property PACKAGE_PIN T15 [get_ports Clk100]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/clk_wiz_0/inst/clk_in1_design_1_clk_wiz_0_0]
#create_clock -period 10.000 -name Clock100Timing -waveform {0.000 5.000} [get_ports Clk100]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN U17 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN V17 [get_ports uart_rtl_0_rxd]
set_property SLEW SLOW [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_ce_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_oen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports emc_rtl_0_wen]
set_property PACKAGE_PIN G17 [get_ports {emc_rtl_0_addr[0]}]
set_property PACKAGE_PIN H16 [get_ports {emc_rtl_0_addr[1]}]
set_property PACKAGE_PIN H18 [get_ports {emc_rtl_0_addr[2]}]
set_property PACKAGE_PIN H17 [get_ports {emc_rtl_0_addr[3]}]
set_property PACKAGE_PIN B16 [get_ports {emc_rtl_0_addr[4]}]
set_property PACKAGE_PIN B15 [get_ports {emc_rtl_0_addr[5]}]
set_property PACKAGE_PIN A15 [get_ports {emc_rtl_0_addr[6]}]
set_property PACKAGE_PIN B14 [get_ports {emc_rtl_0_addr[7]}]
set_property PACKAGE_PIN D10 [get_ports {emc_rtl_0_addr[8]}]
set_property PACKAGE_PIN A9 [get_ports {emc_rtl_0_addr[9]}]
set_property PACKAGE_PIN C16 [get_ports {emc_rtl_0_addr[10]}]
set_property PACKAGE_PIN B9 [get_ports {emc_rtl_0_addr[11]}]
set_property PACKAGE_PIN A14 [get_ports {emc_rtl_0_addr[12]}]
set_property PACKAGE_PIN A10 [get_ports {emc_rtl_0_addr[13]}]
set_property PACKAGE_PIN A13 [get_ports {emc_rtl_0_addr[14]}]
set_property PACKAGE_PIN B11 [get_ports {emc_rtl_0_addr[15]}]
set_property PACKAGE_PIN B12 [get_ports {emc_rtl_0_addr[16]}]
set_property PACKAGE_PIN A12 [get_ports {emc_rtl_0_addr[17]}]
set_property PACKAGE_PIN B10 [get_ports {emc_rtl_0_addr[18]}]
set_property PACKAGE_PIN D8 [get_ports emc_rtl_0_wen]
set_property PACKAGE_PIN A17 [get_ports {emc_rtl_0_oen[0]}]
set_property PACKAGE_PIN C8 [get_ports {emc_rtl_0_ce_n[0]}]




#create_generated_clock -name design_1_i/ClockManager_0/U0/OutBuffer_reg/Q -source [get_ports Clk100] -divide_by 20 [get_pins design_1_i/ClockManager_0/U0/OutBuffer_reg/Q]

set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IP_DATABUS_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_rtl_0_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports IP_CS_0]
set_property IOSTANDARD LVCMOS33 [get_ports IP_DCX_0]
set_property IOSTANDARD LVCMOS33 [get_ports IP_IM0_0]
set_property IOSTANDARD LVCMOS33 [get_ports IP_RD_0]
set_property IOSTANDARD LVCMOS33 [get_ports IP_RESETDisplay_0]
set_property IOSTANDARD LVCMOS33 [get_ports IP_WR_0]
set_property PACKAGE_PIN M17 [get_ports IP_CS_0]
set_property PACKAGE_PIN R18 [get_ports IP_IM0_0]
set_property PACKAGE_PIN P18 [get_ports IP_RD_0]
set_property PACKAGE_PIN R17 [get_ports IP_RESETDisplay_0]
set_property PACKAGE_PIN N17 [get_ports IP_WR_0]
set_property PACKAGE_PIN N18 [get_ports IP_DCX_0]
set_property PACKAGE_PIN J14 [get_ports {IP_DATABUS_0[0]}]
set_property PACKAGE_PIN K15 [get_ports {IP_DATABUS_0[1]}]
set_property PACKAGE_PIN L14 [get_ports {IP_DATABUS_0[2]}]
set_property PACKAGE_PIN M16 [get_ports {IP_DATABUS_0[3]}]
set_property PACKAGE_PIN M15 [get_ports {IP_DATABUS_0[4]}]
set_property PACKAGE_PIN T14 [get_ports {IP_DATABUS_0[5]}]
set_property PACKAGE_PIN T13 [get_ports {IP_DATABUS_0[6]}]
set_property PACKAGE_PIN R13 [get_ports {IP_DATABUS_0[7]}]
set_property PACKAGE_PIN N16 [get_ports {IP_DATABUS_0[8]}]
set_property PACKAGE_PIN N14 [get_ports {IP_DATABUS_0[9]}]
set_property PACKAGE_PIN P16 [get_ports {IP_DATABUS_0[10]}]
set_property PACKAGE_PIN P15 [get_ports {IP_DATABUS_0[11]}]
set_property PACKAGE_PIN R16 [get_ports {IP_DATABUS_0[12]}]
set_property PACKAGE_PIN R15 [get_ports {IP_DATABUS_0[13]}]
set_property PACKAGE_PIN P14 [get_ports {IP_DATABUS_0[14]}]
set_property PACKAGE_PIN M14 [get_ports {IP_DATABUS_0[15]}]
set_property PACKAGE_PIN V14 [get_ports spi_rtl_0_sck_io]
set_property PACKAGE_PIN V12 [get_ports {spi_rtl_0_ss_io[0]}]


set_property IOSTANDARD LVCMOS18 [get_ports BoloTrigger]
set_property PACKAGE_PIN L2 [get_ports BoloTrigger]

set_property PULLUP true [get_ports spi_rtl_0_io0_io]
set_property PULLUP true [get_ports spi_rtl_0_io1_io]
set_property PULLUP true [get_ports spi_rtl_0_io2_io]
set_property PULLUP true [get_ports spi_rtl_0_io3_io]

#create_generated_clock -name design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q -source [get_pins design_1_i/ClockManager_0/ClockOut100Mhz] -divide_by 20 [get_pins design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q]

create_generated_clock -name design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q -source [get_pins design_1_i/clk_wiz_0/clk_out1] -divide_by 4 [get_pins design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q]

set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.PERSIST NO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]


