set_property PACKAGE_PIN B17 [get_ports {emc_rtl_0_dq_io[7]}]
set_property PACKAGE_PIN F18 [get_ports {emc_rtl_0_dq_io[0]}]
set_property PACKAGE_PIN F17 [get_ports {emc_rtl_0_dq_io[1]}]
set_property PACKAGE_PIN E18 [get_ports {emc_rtl_0_dq_io[2]}]
set_property PACKAGE_PIN E17 [get_ports {emc_rtl_0_dq_io[3]}]
set_property PACKAGE_PIN D18 [get_ports {emc_rtl_0_dq_io[4]}]
set_property PACKAGE_PIN C18 [get_ports {emc_rtl_0_dq_io[5]}]
set_property PACKAGE_PIN C17 [get_ports {emc_rtl_0_dq_io[6]}]
set_property PACKAGE_PIN U14 [get_ports spi_rtl_0_io0_io]
set_property PACKAGE_PIN U11 [get_ports spi_rtl_0_io1_io]
set_property PACKAGE_PIN U15 [get_ports spi_rtl_0_io2_io]
set_property PACKAGE_PIN V13 [get_ports spi_rtl_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Clk100]
set_property PACKAGE_PIN T15 [get_ports Clk100]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/clk_wiz_0/inst/clk_in1_design_1_clk_wiz_0_0]
#create_clock -period 10.000 -name Clock100Timing -waveform {0.000 5.000} [get_ports Clk100]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN U17 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN V17 [get_ports uart_rtl_0_rxd]
set_property SLEW SLOW [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_ce_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_dq_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_0_oen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports emc_rtl_0_wen]
set_property PACKAGE_PIN G17 [get_ports {emc_rtl_0_addr[0]}]
set_property PACKAGE_PIN H16 [get_ports {emc_rtl_0_addr[1]}]
set_property PACKAGE_PIN H18 [get_ports {emc_rtl_0_addr[2]}]
set_property PACKAGE_PIN H17 [get_ports {emc_rtl_0_addr[3]}]
set_property PACKAGE_PIN B16 [get_ports {emc_rtl_0_addr[4]}]
set_property PACKAGE_PIN B15 [get_ports {emc_rtl_0_addr[5]}]
set_property PACKAGE_PIN A15 [get_ports {emc_rtl_0_addr[6]}]
set_property PACKAGE_PIN B14 [get_ports {emc_rtl_0_addr[7]}]
set_property PACKAGE_PIN D10 [get_ports {emc_rtl_0_addr[8]}]
set_property PACKAGE_PIN A9 [get_ports {emc_rtl_0_addr[9]}]
set_property PACKAGE_PIN C16 [get_ports {emc_rtl_0_addr[10]}]
set_property PACKAGE_PIN B9 [get_ports {emc_rtl_0_addr[11]}]
set_property PACKAGE_PIN A14 [get_ports {emc_rtl_0_addr[12]}]
set_property PACKAGE_PIN A10 [get_ports {emc_rtl_0_addr[13]}]
set_property PACKAGE_PIN A13 [get_ports {emc_rtl_0_addr[14]}]
set_property PACKAGE_PIN B11 [get_ports {emc_rtl_0_addr[15]}]
set_property PACKAGE_PIN B12 [get_ports {emc_rtl_0_addr[16]}]
set_property PACKAGE_PIN A12 [get_ports {emc_rtl_0_addr[17]}]
set_property PACKAGE_PIN B10 [get_ports {emc_rtl_0_addr[18]}]
set_property PACKAGE_PIN D8 [get_ports emc_rtl_0_wen]
set_property PACKAGE_PIN A17 [get_ports {emc_rtl_0_oen[0]}]
set_property PACKAGE_PIN C8 [get_ports {emc_rtl_0_ce_n[0]}]




#create_generated_clock -name design_1_i/ClockManager_0/U0/OutBuffer_reg/Q -source [get_ports Clk100] -divide_by 20 [get_pins design_1_i/ClockManager_0/U0/OutBuffer_reg/Q]

set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_Data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_rtl_0_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports CS_0]
set_property IOSTANDARD LVCMOS33 [get_ports DCX_0]
set_property IOSTANDARD LVCMOS33 [get_ports IM0_0]
set_property IOSTANDARD LVCMOS33 [get_ports RD_0]
set_property IOSTANDARD LVCMOS33 [get_ports ResetDisplay_0]
set_property IOSTANDARD LVCMOS33 [get_ports WR_0]
set_property PACKAGE_PIN M17 [get_ports CS_0]
set_property PACKAGE_PIN R18 [get_ports IM0_0]
set_property PACKAGE_PIN P18 [get_ports RD_0]
set_property PACKAGE_PIN R17 [get_ports ResetDisplay_0]
set_property PACKAGE_PIN N17 [get_ports WR_0]
set_property PACKAGE_PIN N18 [get_ports DCX_0]
set_property PACKAGE_PIN J14 [get_ports {LCD_Data_0[0]}]
set_property PACKAGE_PIN K15 [get_ports {LCD_Data_0[1]}]
set_property PACKAGE_PIN L14 [get_ports {LCD_Data_0[2]}]
set_property PACKAGE_PIN M16 [get_ports {LCD_Data_0[3]}]
set_property PACKAGE_PIN M15 [get_ports {LCD_Data_0[4]}]
set_property PACKAGE_PIN T14 [get_ports {LCD_Data_0[5]}]
set_property PACKAGE_PIN T13 [get_ports {LCD_Data_0[6]}]
set_property PACKAGE_PIN R13 [get_ports {LCD_Data_0[7]}]
set_property PACKAGE_PIN N16 [get_ports {LCD_Data_0[8]}]
set_property PACKAGE_PIN N14 [get_ports {LCD_Data_0[9]}]
set_property PACKAGE_PIN P16 [get_ports {LCD_Data_0[10]}]
set_property PACKAGE_PIN P15 [get_ports {LCD_Data_0[11]}]
set_property PACKAGE_PIN R16 [get_ports {LCD_Data_0[12]}]
set_property PACKAGE_PIN R15 [get_ports {LCD_Data_0[13]}]
set_property PACKAGE_PIN P14 [get_ports {LCD_Data_0[14]}]
set_property PACKAGE_PIN M14 [get_ports {LCD_Data_0[15]}]
set_property PACKAGE_PIN V14 [get_ports spi_rtl_0_sck_io]
set_property PACKAGE_PIN V12 [get_ports {spi_rtl_0_ss_io[0]}]


#set_property IOSTANDARD LVCMOS18 [get_ports BoloTrigger]
#set_property PACKAGE_PIN L2 [get_ports BoloTrigger]

set_property PULLUP true [get_ports spi_rtl_0_io0_io]
set_property PULLUP true [get_ports spi_rtl_0_io1_io]
set_property PULLUP true [get_ports spi_rtl_0_io2_io]
set_property PULLUP true [get_ports spi_rtl_0_io3_io]

#create_generated_clock -name design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q -source [get_pins design_1_i/ClockManager_0/ClockOut100Mhz] -divide_by 20 [get_pins design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q]

#create_generated_clock -name design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q -source [get_pins design_1_i/clk_wiz_0/clk_out1] -divide_by 4 [get_pins design_1_i/Display_top_0/U0/Display_Control_inst/clock_Div_reg/Q]

set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.PERSIST NO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]



#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[15]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[4]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[17]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[11]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[22]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[24]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[19]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[31]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[26]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[28]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[12]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[9]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[8]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[14]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[9]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[7]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[15]}]
#set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_1_M_AXIS_MM2S_TREADY]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_1_M_AXIS_TREADY]
#set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_1_M_AXIS_MM2S_TLAST]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[5]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[10]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[12]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[5]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[13]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[16]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[18]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[14]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[23]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[25]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[20]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[21]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[30]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[27]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[29]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[13]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[6]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[7]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[10]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[8]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[6]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[11]}]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_1_M_AXIS_TLAST]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_1_M_AXIS_TVALID]
#set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_1_M_AXIS_MM2S_TVALID]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[4]}]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 32 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[0]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[1]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[2]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[3]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[4]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[5]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[6]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[7]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[8]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[9]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[10]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[11]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[12]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[13]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[14]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[15]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[16]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[17]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[18]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[19]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[20]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[21]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[22]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[23]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[24]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[25]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[26]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[27]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[28]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[29]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[30]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TDATA[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 16 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[0]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[1]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[2]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[3]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[4]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[5]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[6]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[7]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[8]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[9]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[10]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[11]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[12]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[13]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[14]} {design_1_i/axis_dwidth_converter_1_M_AXIS_TDATA[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 4 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[0]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[1]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[2]} {design_1_i/axi_dma_1_M_AXIS_MM2S_TKEEP[3]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 1 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axi_dma_1_M_AXIS_MM2S_TLAST]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 1 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_dma_1_M_AXIS_MM2S_TREADY]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_dma_1_M_AXIS_MM2S_TVALID]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 1 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_dwidth_converter_1_M_AXIS_TLAST]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_dwidth_converter_1_M_AXIS_TREADY]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_dwidth_converter_1_M_AXIS_TVALID]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
