
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbindata.h"

/*
* The configuration table for devices
*/

XBindata_Config XBindata_ConfigTable[XPAR_XBINDATA_NUM_INSTANCES] =
{
	{
		XPAR_BINDATA_0_DEVICE_ID,
		XPAR_BINDATA_0_S_AXI_CRTL_BUS_BASEADDR
	}
};


